# Generated by Django 5.2.7 on 2026-04-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0004_alter_requestservice_id_alter_requestsparepart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('technician', 'Техник'), ('employee', 'Сотрудник'), ('manager', 'Руководитель')], max_length=250, unique=True, verbose_name='Наименование'),
        ),
    ]
