# Generated by Django 5.2.7 on 2026-04-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0005_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='assigned_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.office', verbose_name='Закрепленный кабинет'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='configuration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приобретения'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='office',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.building', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
